### ISSUE TITLE
Document BigQuery flattening workaround

### ISSUE THREAD

**Issue by arostamianfar** [googlegenomics/gcp-variant-transforms#191]
See snarfed's comment in #92 for context.

**Comment by bashir2** [comment]
I am curious about the priority of this issue. If it is P1, can we add some more context either here or in #92 about use cases that this is needed for? Then maybe we can decide to treat the actual implementation (i.e., Issue #92) as a P1?

Just to be clear: I think this is a useful option because it basically forces all rows to have a single allele and beside other benefits, it has implications for annotations too. So if there is enough justification, I like the implementation to be P1 and maybe we can close this documentation-only issue.

**Comment by arostamianfar** [comment]
The main motivation is that some tools like Tableau do not support repeated records, so users currently need the workaround that is mentioned in #92. However, we don't have bandwidth to take on the implementation in Q2 (we should do it properly and build the foundations in VT to support multiple schemas), which is why we decided to just document the workaround in Q2.
