### ISSUE TITLE
VEP logs get written to wrong location if trailing slash is in --annotation_output_dir

### ISSUE THREAD

**Issue by Jessime** [googlegenomics/gcp-variant-transforms#286]
If I do `--annotation_output_dir gs://jessime_test_bucket/vep_test/` instead of `--annotation_output_dir gs://jessime_test_bucket/vep_test`, then the log file gets written to the base directory. 

The fix should be as simple as changing:

```python
  def _get_output_log_path(self, output_dir, vm_index):
    # type: (str, int) -> str
    return '{}/logs/output_VM_{}.log'.format(output_dir, vm_index)
```

to

```python
  def _get_output_log_path(self, output_dir, vm_index):
    # type: (str, int) -> str
    return filesystems.FileSystems.join(output_dir, 'logs/output_VM_{}.log'.format(vm_index))
```

But I'm going to have to figure out testing before I can make the change.

**Comment by bashir2** [comment]
Thanks @Jessime for reporting and figuring out the root cause. All remote file manipulation in [vep_runner](https://github.com/googlegenomics/gcp-variant-transforms/blob/master/gcp_variant_transforms/libs/annotation/vep/vep_runner.py) should preferably use the filesystems module. I should have missed this one but please fix anything else if you find any while looking at this module (BTW, the `/` after `logs` should be added by join too) .
