### ISSUE TITLE
Zone/region error when calling genomics pipeline

### ISSUE THREAD

**Issue by hannes-brt** [googlegenomics/gcp-variant-transforms#312]
Calling the Google Genomics Pipelines submission script in the README as is, currently gives the following error:

`ERROR: (gcloud.alpha.genomics.pipelines.run) INVALID_ARGUMENT: Error: validating pipeline: zones and regions cannot be specified together`

Neither removing the `--zones` arg, replacing `--zones` with `--regions`, nor using `--zones` and `--regions` together works.

~~Also, when I run with Dataflow but without Genomics Pipelines, my workers fail to start with the following error:~~

~~`apache_beam.runners.worker.operations.Operation has the wrong size, try recompiling. Expected 128, got 136`~~

(Edit: This turned out to be a version mismatch issue)

**Comment by arostamianfar** [comment]
Hi Hannes,

Are you referring to [this doc](https://github.com/googlegenomics/gcp-variant-transforms/blob/master/docs/setting_zone_region.md)? I just tried it and it works. It's possible that you may be using an older version of gcloud or our documentation; please run `gcloud components update` to ensure you have the latest version.

Note that Dataflow requires both `--zone` and `--region`, but the pipelines API only accepts one of `--zones` or `--regions`. We have since updated the documentation to reflect this (#275).

P.S. we recently updated our docs to use the Pipelines v2alpha1 (instead of v1alpha2); you no longer need to provide the yaml file separately.

Let us know if you're still experiencing issues!

**Comment by arostamianfar** [comment]
Update: we just ran into the same issue when only specifying the `--zones` flag. It turns out that if you have `region` defined as part of `gcloud config` [*] then it uses that value by default (even if unspecified).

Workaround: run `gcloud config set compute/region ""`
Longer term solution: we'll look into ways to not use the default region flag from gcloud.

[*] To determine if this is the issue:
Run `gcloud config list` and see if it returns a value for `region`:
```
[compute]
region = us-east1
zone = us-east1-b
...
```

Please re-open if you continue seeing this issue.

**Comment by avihoo** [comment]
@hannes-brt Sorry for posting here late but I just hit with the ```apache_beam.runners.worker.operations.Operation has the wrong size, try recompiling. Expected 128, got 136``` issue.

Any chance you can elaborate a bit about the version mismatch and how you solved it?

**Comment by allieychen** [comment]
@avihoo , Can you try the[ workaround ](https://github.com/googlegenomics/gcp-variant-transforms/issues/312#issuecomment-415125917)mentioned above?

**Comment by avihoo** [comment]
Hey @allieychen I managed to get this sorted. We had an issue where two versions of Apache beam were clashing (2.10 and 2.11), aligning to the same version fixed the issue. Thanks!
