### ISSUE TITLE
Add an option to specify filename per call

### ISSUE THREAD

**Issue by arostamianfar** [googlegenomics/gcp-variant-transforms#398]
There are certain use cases where users need to distinguish between call names (perhaps even having the same ID), so having the filename as one of the columns would be super useful (e.g. call.filename).

See https://groups.google.com/forum/#!topic/google-genomics-discuss/ODrX6H6B48c for context.

We also need to ensure to exclude this new column when running BQ -> VCF.

**Comment by smrgit** [comment]
@allieychen (since @arostamianfar has left) -- do you know if/when this might be implemented/released?  it would be very very useful!  thx!

**Comment by kemp-google** [comment]
@smrgit we will try to prioritize for early in Q1.  I'll post another update in early January.

**Comment by smrgit** [comment]
any news on this enhancement request? @kemp-google

**Comment by allieychen** [comment]
one use case: https://groups.google.com/forum/#!topic/google-genomics-discuss/hWUBDsiBeTE

**Comment by smrgit** [comment]
another use case is where there are multiple VCFs even for the exact same sample (or pair of samples) -- based on different bam files or different aligners or different versions of the code, etc

as a generalization of including the input VCF uri in a new column, on each row of the table written to BigQuery, I suggest that the --input_file option (#441 and also my suggestion) be extended to be able to include a 2nd column in that file where the 1st column is an input file name (or pattern) and the 2nd column is a "flag" or "tag" to be added to the resulting BigQuery table for each call from each corresponding file

the reasoning is that although an input VCF uri is probably a good and unique identifier, the user may prefer to specify the associated file GUID -- etc

**Comment by kemp-google** [comment]
Hi Sheila,

Sorry for the delay on this.

The reason we have not implemented it yet is because we're worried about the increase in query cost that would result if we just add more data into each call.

In particular, filenames would represent a much larger source of data than the existing data stored in the calls.  Since BigQuery charges based on the amount of data scanned, this would result in queries being more expensive.

We'd like, instead, to get this auxiliary data out into another table and allow you to do JOINs.  This is complicated by the need for a stable join key.  We're looking into this now.

**Comment by smrgit** [comment]
Thanks for that comment @kemp-google -- when computing the amount of data scanned, if the query includes a repeated record, does the total amount of data include the _total size of all occurrences of that record_ even if you're just pulling out one field?  If that's the case, maybe the filename could be included in a "companion" repeated record that is repeated the same # of times as the "call" record but is a separate record? (and of course it would be optional) -- this way you wouldn't need to create a unique identifier / stable join key.  But perhaps you have already thought of this and ruled it out for other reasons?

**Comment by smrgit** [comment]
btw, one thing that I have done as a work-around is to "hack" the sample identifiers to include additional information that I extract from the meta-header so that the sample ID in the `#CHROM` header looks like this: `sampleID;info1;info2` and then I can later parse that easily in BigQuery (assuming that the `;` character is not used in any of the other strings) -- but of course this requires touching/editing every single VCF file...

**Comment by kemp-google** [comment]
Yes I did consider the option of storing it as a "companion" column but you will still end up paying to scan all the filename data if you are reading it.  So it won't impact users that won't use the filename column but you would end up incurring costs for scanning *all* filenames stored, which, again is a large amount of data relative to what we are otherwise storing.

**Comment by smrgit** [comment]
I'm excited to see progress on this -- it looks like #495 is close to being merged and released -- yes?

**Comment by kemp-google** [comment]
Hi Sheila,

We are still evaluating options for normalization of the core tables, which will influence this feature.

So, "close" is perhaps over optimistic, but this is definitely our top priority at the moment.

**Comment by samanvp** [comment]
@smrgit This feature is now included in our [latest release](https://github.com/googlegenomics/gcp-variant-transforms/releases/tag/v0.9.0). Set
```
--sample_name_encoding WITH_FILE_PATH
```
to assign a unique `sample_id` to each sample. 

Hope this help with your use case and sorry for slow response.
