### ISSUE TITLE
enhancement request: support input_list (file) option

### ISSUE THREAD

**Issue by smrgit** [googlegenomics/gcp-variant-transforms#441]
the idea is that a list of VCF objects in GCS which don't easily match a particular "pattern" would be passed in as a list (one object url per line in the file) using an --input_list option rather than the current --input_pattern

**Comment by tneymanov** [comment]
Hi Sheila, apologies for delay.

This functionality has been introduced in release 0.7.0.

Instead of providing a list, we introduced a flag --input_file, which takes a file that consists of patterns or file names, with 1 pattern/file per line. Only one of input_file or input_pattern can be supplied at the same time. Note that when dealing with smaller amount of files, this functionality is generally slightly slower than providing a single input pattern, even if they span the same files. This drop in speed won't be present if your input_file has only 1 pattern in it, as functionality would be identical to supplying that pattern directly in input_pattern flag.

Thanks.

Closing the thread.
