### ISSUE TITLE
Use in Cloud Function

### ISSUE THREAD

**Issue by Rokshan2016** [googlegenomics/gcp-variant-transforms#543]
Hi @samanvp 
Can I use this library in cloud function?

**Comment by samanvp** [comment]
Unfortunately no.
Currently the easiest way to run Variant Transforms is using our docker image. It's a fairly easy process, you only need to copy your VCF files into a Google Cloud Storage bucket and then follow [these instructions](https://github.com/googlegenomics/gcp-variant-transforms#using-docker).

The reasons we don't have a Cloud Function runner are:
* Speed: currently we use [Apache Beam](https://beam.apache.org/) to read and process VCF files which is much faster because we parallelize the job on hundreds of workers.
* Cloud Function limitations: we need many different tools in our docker image to run Variant Transforms (see our [`Dockerfile`](https://github.com/googlegenomics/gcp-variant-transforms/blob/master/docker/Dockerfile) and [`setup.py`](https://github.com/googlegenomics/gcp-variant-transforms/blob/master/setup.py)) which is not possible to include in Cloud Functions. Also Cloud Functions can only run for 540 seconds before they are [forcibly terminated](https://cloud.google.com/functions/quotas#time_limits).

Having said this, we envision sometime in future we use cloud function to *trigger* Variant Transforms. In that setting user only needs to point the Cloud Function to their storage bucket; adding a new VCF file to the bucket will trigger the Variant Transforms and it will automatically import all the variants into the destination BigQuery table. That way we will isolate users from details of how to set up and launch Variant Transforms.

Please let me know if you have any problem to run Variant Transforms by following the instructions that I mentioned earlier. We'd gladly help you with any issue.

**Comment by Rokshan2016** [comment]
@samanvp 
I want to trigger execution remotely . e.g. Docker image in GCP. My VCF files are in GCS. I want to trigger this docker image from another application.

**Comment by samanvp** [comment]
Where is your application running? 
If your application is running on a GCE machine with all needed permissions granted, you could still follow [the instructions I mentioned earlier](https://github.com/googlegenomics/gcp-variant-transforms#using-docker). That `docker run ...` line would use [Cloud Life Sciences API](https://cloud.google.com/life-sciences/docs/concepts/introduction) to spin up another worker to launch and monitor the Variant Transforms job.

Alternatively, you could skip the extra worker (and some other permissions needed by Cloud Life Sciences API) by modifying the commands as follows:
```
GOOGLE_CLOUD_PROJECT=...
GOOGLE_CLOUD_REGION=...
INPUT_PATTERN=gs://.../*.vcf
OUTPUT_TABLE=...
TEMP_LOCATION=gs://...

COMMAND="/opt/gcp_variant_transforms/bin/vcf_to_bq \
  --input_pattern "${INPUT_PATTERN}" \
  --output_table "${OUTPUT_TABLE}" \
  --temp_location "${TEMP_LOCATION}" \
  --job_name vcf-to-bigquery \
  --project "${GOOGLE_CLOUD_PROJECT}" \
  --region "${GOOGLE_CLOUD_REGION}" \
  --runner DataflowRunner"

docker run  -v ~/.config:/root/.config \
  gcr.io/cloud-lifesciences/gcp-variant-transforms \
  "${COMMAND}"
```
Later today I will try this command myself and make sure it is working as intended.

**Comment by Rokshan2016** [comment]
@samanvp Thanks . My application is running in GKE. Its a simple python rest API . I am trying to call this in my rest API.
