### ISSUE TITLE
Using data from GCS Bucket

### ISSUE THREAD

**Issue by acheketa** [googlegenomics/gcp-variant-transforms#546]
Hi!

I'm trying to figure out how to use GCS Bucket with a custom Python script in a custom docker.

In your process, do you use `gsutil cp` in the shell to download the input file in the working VM?
Or do you use the Python library `google.cloud.storage` to do so in the script?

Thanks.

**Comment by samanvp** [comment]
Hi @acheketa 
As I understand your question is about how to read objects from a GCS bucket. There are multiple ways to do that:
* As you mentioned `gsutil cp` is way but you need to make sure the worker that runs that command has permissions to access the bucket.
* Another way is to import `google.cloud.storage` library and use it to read from a bucket.
* In Variant Transforms code base, since we are using Apache Beam to read VCF files we [use](https://github.com/googlegenomics/gcp-variant-transforms/blob/4394cde8c104b362fb2837df513ef97dc69b4679/gcp_variant_transforms/beam_io/vcf_parser.py#L301) `apache_beam.io.textio._TextSource` which can read both from GCS and local disk.
* Another solution is to use [gcsfuse](https://github.com/GoogleCloudPlatform/gcsfuse) which allows you to mount a GCS bucket and access it as local disk.
* Finally, if you are tying to use a tool that already exists in a docker image, you can use [Google Life Sciences API](https://cloud.google.com/life-sciences/docs/reference/rest/) which basically given a command and docker image will run you the tool. The main benefit of using it is automatic localization of inputs and copying output files and logs back to a destination GCS bucket. [Here](https://github.com/googlegenomics/pipelines-tools/blob/41825beb7587be6e5dcd364f2fc19ca64bd838cc/pipelines/internal/commands/run/run.go#L153) you can see an example of how to set input values.

There are many good tutorials and documentations how to implement each of these solutions.

If you have any specific question about Variant Transforms please do not hesitate to file another issue.
