### ISSUE TITLE
Read VCF File From GCS Bucket

### ISSUE THREAD

**Issue by Rokshan2016** [googlegenomics/gcp-variant-transforms#547]
@samanvp  
I have a use case to read VCF file from GCS and extract this String "FORMAT SRR1518011"  .  I am trying to use google cloud storage lib 

blob1 = bucket.get_blob('variants/hc.vcf.gz')
s = gzip.decompress(blob1.download_as_string())
print(s)

It is not giving  the header information .  Any suggestion please

**Comment by samanvp** [comment]
I can explain how we read compressed VCF files in VariantTransforms:

- We make sure each compressed VCF file is accompanied by its index file (`.tbi`):
https://github.com/googlegenomics/gcp-variant-transforms/blob/dd79dc59edbe204153cb48c78297fc39fd6f5e30/gcp_variant_transforms/pipeline_common.py#L224
- Then we read files using a PTransform named ReadFromBGZF: https://github.com/googlegenomics/gcp-variant-transforms/blob/dd79dc59edbe204153cb48c78297fc39fd6f5e30/gcp_variant_transforms/beam_io/vcfio.py#L276
- The main work in done in `_read_records` where a `file_path` and a `block` is sent to `PySamParser`:
https://github.com/googlegenomics/gcp-variant-transforms/blob/dd79dc59edbe204153cb48c78297fc39fd6f5e30/gcp_variant_transforms/beam_io/vcf_parser.py#L406
- In the parser we use `beam_io.bgzf` module to read the given block from the compressed file:
https://github.com/googlegenomics/gcp-variant-transforms/blob/dd79dc59edbe204153cb48c78297fc39fd6f5e30/gcp_variant_transforms/beam_io/vcf_parser.py#L279
- Finally `_process_header_lines` read the header lines and send them to the PySam object:
https://github.com/googlegenomics/gcp-variant-transforms/blob/dd79dc59edbe204153cb48c78297fc39fd6f5e30/gcp_variant_transforms/beam_io/vcf_parser.py#L327

As you can see since we use beam library and `beam_io.bgzf` module, we don't need to worry whether the file is located in a GCS bucket or in the local disk.

I think to deal with your issue you need to make sure: 
1. you can read the compressed VCF file and get that header line when the file is located in the local disk.
2. find a way to localized the file from GCS bucket and then read the header. Actually a few days ago someone else asked a similar [question about how to localize an object from GCS bucket](https://github.com/googlegenomics/gcp-variant-transforms/issues/546). Please take a look and see if my answer can help in any way.

Could you please explain what is your use case? If it's a feature that many customers need it we might be able to prioritize to implement in Variant Transforms sometime in future.

**Comment by samanvp** [comment]
I am going to close this issue. If you still need help with this please feel free to continue commenting on this thread.
