### ISSUE TITLE
off by 1 error?

### ISSUE THREAD

**Issue by bradmonk** [googlegenomics/gcp-variant-transforms#694]
This may not be the right place to flag this issue, but I don't know where else to start... 

All the variant start positions are off-by-one in the BigQuery gnomad exome dataset compared to the [gnomad browser](https://gnomad.broadinstitute.org/) (their web-based gene/variant lookup portal), and also the raw [vcf files](https://gnomad.broadinstitute.org/downloads#v2-variants).

The gnomAD dataset was recently made available on BigQuery (see google [cloud marketplace](https://console.cloud.google.com/marketplace/product/broad-institute/gnomad) and [blog post](https://cloud.google.com/blog/topics/healthcare-life-sciences/google-cloud-providing-free-access-to-genome-aggregation-database?hl=en_US) announcements). On the market place page it mentions

> _Variant Transforms was used to process these VCF files and import them to BigQuery. VEP annotations were parsed into separate columns for easier analysis using Variant Transforms’ annotation support ._

This issue may not have anything to do with this Variant Transform and Annotation code repo. But like I mentioned, I don't know where else to mention it (ideas?). Quickly reproduce the issue by running [this gist code](https://gist.github.com/bradmonk/a909251c0bcc36476f0b6356321814bd) in the BigQuery editor. Then navigate to the [gnomad website](https://gnomad.broadinstitute.org/) and lookup the gene: _PAPLN_ (or just check out the attached screenshot).

Thanks for your time!
b

![BigQuery_Gnomad_OffByOne](https://user-images.githubusercontent.com/3250505/97597697-22a60980-19d4-11eb-81c8-edcb05370a50.png)

**Comment by bradmonk** [comment]
I see now that the gnomad website is annotated by end position, not start position. Problem solved, I think.

**Comment by samanvp** [comment]
Hi @bradmonk and sorry for late response.
I think the root of this discrepancy is due to the underlying [coordinate systems](biostars.org/p/84686/); in Variant Transforms we use 0-based coordinate by default while in the gnomAD browser they are using 1-based coordinate. You can confirm this by comparing variants in our BigQuery tables versus the VCF files. Here are the top 3 variants on chromosomeY 2.1.1 exome:
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER
Y       2654979 rs781744002     G       C       4781.45 PASS
Y       2655003 rs750874990     C       G       729.42  PASS
Y       2655009 rs1327055451    A       G       2172.34 PASS
```

And here is our BigQuery table:
<img width="1118" alt="Screen Shot 2020-11-09 at 10 03 19 AM" src="https://user-images.githubusercontent.com/28307198/98557959-df208a80-2272-11eb-81ac-0bbf2ee80b33.png">

Hope this helps.

**Comment by samanvp** [comment]
As you might know, we have put together a [Jupyter notebook](https://github.com/googlegenomics/gcp-variant-transforms/tree/master/docs/sample_queries) with couple of sample queries to extract information from gnomAD tables. If you have queries that you'd like to share with the rest of community we would be more than happy to add them to that page.

Thank you!
